# Generated by Django 3.2.7 on 2021-09-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_cover', models.CharField(max_length=20)),
                ('book_author', models.CharField(default='abc', max_length=20)),
                ('publisher', models.CharField(default='def', max_length=20)),
                ('published_year', models.IntegerField(default=123)),
            ],
        ),
    ]
